spring.application.name=qacraft-test-management
spring.datasource.url=jdbc:postgresql://localhost:5432/qa-test-management
spring.datasource.username=postgres
spring.datasource.password=02541369
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
